development:
  adapter: postgresql
  host: localhost
  database: back_monkey_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: back_monkey_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: back_monkey
  pool: 5
  timeout: 5000